name: weather_app
description: Weather App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^9.0.1
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf

    - family: Edu
      fonts:
        - asset: fonts/EduVICWANTBeginner-VariableFont_wght.ttf

    - family: MPL
      fonts:
        - asset: fonts/MPLUSRounded1c-Regular.ttf